### ISSUE TITLE
When you publish to Azure Web Site, you get a AADSTS50001:  Resource ... is not registered for the account

### ISSUE THREAD

**Issue by mmushatt** [AzureADSamples/NativeClient-DotNet#12]
The sample worked fine locally, but, once it was pushed to an Azure Web Site, when you start the client using the instructions listed, I received a 

"AADSTS50001: Resource 'https://xxxxxx' is not registered for the account.

error.  To resolve this error, I had to ensure that the “APP ID URI” value (single sign-on section) of the Azure portal, was copied to the following values prior to publishing the site.

web.config :  <add key="ida:Audience" value="<copied value> " />
app.config :  <add key="todo:TodoListResourceId" value="<copied value>" />
app.config :  <add key="todo:TodoListBaseAddress" value="<copied value>" />

Once this was corrected, the native client worked as expected with the Azure published site.

**Comment by dstrockis** [comment]
Hey @mmushatt.  The message didn't quite come through.  But yes, you should have to add the App ID URI in [this line](https://github.com/AzureADSamples/NativeClient-DotNet/blob/master/TodoListService/Web.config#L13) before the sample will work locally or on Azure.

**Comment by mmushatt** [comment]
Sorry about the message did not totally come across.  The reason why I mention it is because a customer followed the sample last week and it worked locally.  When they published it, it failed with the “AADSTS50001: Resource 'https://xxxxxxxxx’  is not registered for the account” error.  I then troubleshot the issue with him and discovered that he did not make the changes when it was published.  He told he followed the sample and it did not work.  I just wanted to let you know in case others run into the same problem with the sample.

~ Michael Cedric Mushatt

**Comment by dstrockis** [comment]
Ok, thanks @mmushatt.  Going to close this for now but I'll keep an eye out for similar issues.
