### ISSUE TITLE
questions about instructions

### ISSUE THREAD

**Issue by yamspog** [AzureADSamples/NativeClient-DotNet#8]
In the instruction document it has the following line:

4.Find the app key  ida:RedirectUri  and replace the value with the Redirect URI for the TodoListClient from the Azure portal, for example  http://TodoListClient .

However, there is no ida:RedirectUri to be found in the code.  Wondering what happened to this key and if it is important?

**Comment by skwan** [comment]
See https://github.com/AzureADSamples/NativeClient-DotNet/blob/master/TodoListClient/MainWindow.xaml.cs, line 58:

Uri redirectUri = new Uri(ConfigurationManager.AppSettings["ida:RedirectUri"]);
